refactor: Use state for NBT encoder (#134)
Like we already do for the NBT de-coder, we now keep track of the
state of NBT encoding, such as the stack of compound/list tags up to
the current level. For now, the only benefit is additional correctness
checks, but once encoding of list tags is added, we will use it more
concretely.

Furthermore, this patch combines the "Encode-NamedXYZ" and
"Encode-XYZ" subroutines into a single one with optional arguments
for the name and name length, to reduce the amount of
semi-duplicate code needed.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -24,4 +24,4 @@ jobs:
         # By specifying "bash" explicitly, GitHub uses the "-eo pipefail" option.
         # See: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
         shell: bash
-        run: "make test | tee test.log; (grep -q FAIL test.log && exit 1 || exit 0)"
+        run: "make test | tee test.log; (grep -q \"FAIL\\|ERROR\" test.log && exit 1 || exit 0)"
